[option]
exclude_paths = []

[rules]
function_same_as_system_function = true
case_default = true
enum_with_type = true
tab_character = true
parameter_in_package = true
function_with_automatic = true
legacy_always = true
non_ansi_module = true
genvar_declaration = false
inout_with_tri = false
level_sensitive_always = false
loop_variable_declaration = false
priority_keyword = false
wire_reg = false
generate_keyword = false
for_with_begin = false
unique0_keyword = false
unique_keyword = false
generate_for_with_label = false
generate_if_with_label = false
interface_port_with_modport = false
output_with_var = false
input_with_var = false
if_with_begin = false
blocking_assignment_in_always_ff = true
non_blocking_assignment_in_always_comb = true
